version: '1.0.1'
services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SMA
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - sma
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sma-api
    command: bash -c "cd app && alembic upgrade head && alembic revision --autogenerate && alembic upgrade head && python endpoint.py"
    ports:
      - "4000:4000"
    depends_on:
      postgres:
              condition: service_healthy
    networks:
      - sma
volumes:
  postgres-db:
networks:
  sma:
